services:
  # Backend API
  - type: web
    name: explorer-api
    env: bun
    rootDir: backend/explorer/api
    plan: free
    buildCommand: bun install
    startCommand: bun run prod:api
    postDeployCommand: bun run generate:env && bun run db:migrate && bun run db:seed
    envVars:
      - key: NODE_ENV
        value: production

  # Frontend Vue
  - type: web
    name: explorer-frontend
    env: bun
    rootDir: frontend/explorer
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run preview
    envVars:
      - key: VITE_API_URL
        value: https://yoexplorer-api.onrender.com